from MyFuckingScanner import MyFuckingScanner
from MyParser import MyParser

if __name__ == "__main__":
    scanner = MyFuckingScanner("input.txt")
    parser = MyParser(scanner)
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())
    print(scanner.get_next_token())

    # parser.diagram_transition(parser.main_node, "Program")
